### ISSUE TITLE
Writing 16GB image on 32GB SD unable to resize in ext4

### ISSUE THREAD

**Issue by SoftwareMagicIT** [DynamicDevices/DiskImager#1]
If I write img file from 16GB image I can't resize this in 32GB image, because df -h return 16GB but parted says 32GB used

**Comment by ajlennon** [comment]
That's interesting thanks. Happy to receive a PR but to be honest I find that the SD writing ecosystem is pretty healthy now. I tend to use Etcher myself

**Comment by SoftwareMagicIT** [comment]
Thanks, but I need to automatize SD write in my company for the monkeys :-p I need to use custom software. Currently I create SD image with 32disk imager. At this time I'm tryng to generare img with your software for seeing if issue persist without using mbr flag!

**Comment by ajlennon** [comment]
Wouldn't dd work?

**Comment by SoftwareMagicIT** [comment]
No, I'll explain. I made a raspberry based device. But this device needs to be initialized every time the SD is written. Who has to clone it does not know linux. So your program is fine because I add the writing of two files in the boot folder of the startup which are then used by the software contained in ext4. It is unthinkable that those who work there have access to the file system. I used a raspberry because I could have made an ESP32 do the same job, only that with the raspberry I already had 80% of the code developed. Since whoever has to do the sd is at the distance of a trip by ship or plane and it's not me and this doesn't know linux ... Do you understand?

**Comment by SoftwareMagicIT** [comment]
found solution using resize2fs into linux at first start.
